//! The full aida schema generated by `sql_generator.zig`. In its own file
//! because it stays RED (a compile error) until the composite type: a compile
//! error in a test file stops every test of that file, so here it does not
//! hold back the rest of the generator tests.

const std = @import("std");
const aida = @import("aida");
const sql = @import("sql_generator");
const expectEqualStrings = std.testing.expectEqualStrings;

// RED until the composite type: clases and mesas have `fecha`, a struct,
// which sqlTypeOf does not map yet. The fecha lines below are a placeholder
// to be replaced by the composite type.
const aida_schema_ddl = sql.schemaSql(aida.type_defs, aida.entity_defs);

test "generates the full aida schema: one CREATE TABLE per entity, in declaration order" {
    try expectEqualStrings(
        \\CREATE TABLE docentes (
        \\    docente TEXT NOT NULL,
        \\    apellido TEXT NOT NULL,
        \\    nombres TEXT NOT NULL,
        \\    cargo TEXT,
        \\    email TEXT,
        \\    email_alternativo TEXT,
        \\    jefe TEXT,
        \\    PRIMARY KEY (docente),
        \\    FOREIGN KEY (jefe) REFERENCES docentes(docente)
        \\);
        \\
        \\CREATE TABLE materias (
        \\    materia TEXT NOT NULL,
        \\    denominacion TEXT NOT NULL,
        \\    PRIMARY KEY (materia),
        \\    UNIQUE (denominacion)
        \\);
        \\
        \\CREATE TABLE periodos (
        \\    periodo TEXT NOT NULL,
        \\    PRIMARY KEY (periodo)
        \\);
        \\
        \\CREATE TABLE cursos (
        \\    periodo TEXT NOT NULL,
        \\    materia TEXT NOT NULL,
        \\    docente TEXT,
        \\    PRIMARY KEY (periodo, materia),
        \\    FOREIGN KEY (periodo) REFERENCES periodos(periodo),
        \\    FOREIGN KEY (materia) REFERENCES materias(materia),
        \\    FOREIGN KEY (docente) REFERENCES docentes(docente)
        \\);
        \\
        \\CREATE TABLE clases (
        \\    periodo TEXT NOT NULL,
        \\    materia TEXT NOT NULL,
        \\    orden BIGINT NOT NULL,
        \\    fecha TEXT,
        \\    tema TEXT,
        \\    PRIMARY KEY (periodo, materia, orden),
        \\    FOREIGN KEY (periodo, materia) REFERENCES cursos(periodo, materia)
        \\);
        \\
        \\CREATE TABLE alumnos (
        \\    alumno TEXT NOT NULL,
        \\    apellido TEXT NOT NULL,
        \\    nombres TEXT NOT NULL,
        \\    email TEXT,
        \\    PRIMARY KEY (alumno)
        \\);
        \\
        \\CREATE TABLE preguntas (
        \\    periodo TEXT NOT NULL,
        \\    materia TEXT NOT NULL,
        \\    orden BIGINT NOT NULL,
        \\    pregunta BIGINT NOT NULL,
        \\    formulacion TEXT NOT NULL,
        \\    aclaraciones TEXT,
        \\    tipo_respuesta TEXT NOT NULL,
        \\    PRIMARY KEY (periodo, materia, orden, pregunta),
        \\    FOREIGN KEY (periodo, materia, orden) REFERENCES clases(periodo, materia, orden)
        \\);
        \\
        \\CREATE TABLE opciones (
        \\    periodo TEXT NOT NULL,
        \\    materia TEXT NOT NULL,
        \\    orden BIGINT NOT NULL,
        \\    pregunta BIGINT NOT NULL,
        \\    opcion TEXT NOT NULL,
        \\    detalle TEXT,
        \\    PRIMARY KEY (periodo, materia, orden, pregunta, opcion),
        \\    FOREIGN KEY (periodo, materia, orden, pregunta) REFERENCES preguntas(periodo, materia, orden, pregunta)
        \\);
        \\
        \\CREATE TABLE inscripciones (
        \\    periodo TEXT NOT NULL,
        \\    materia TEXT NOT NULL,
        \\    alumno TEXT NOT NULL,
        \\    PRIMARY KEY (periodo, materia, alumno),
        \\    FOREIGN KEY (periodo, materia) REFERENCES cursos(periodo, materia),
        \\    FOREIGN KEY (alumno) REFERENCES alumnos(alumno)
        \\);
        \\
        \\CREATE TABLE presencias (
        \\    periodo TEXT NOT NULL,
        \\    materia TEXT NOT NULL,
        \\    alumno TEXT NOT NULL,
        \\    orden BIGINT NOT NULL,
        \\    PRIMARY KEY (periodo, materia, alumno, orden),
        \\    FOREIGN KEY (periodo, materia, alumno) REFERENCES inscripciones(periodo, materia, alumno),
        \\    FOREIGN KEY (periodo, materia, orden) REFERENCES clases(periodo, materia, orden)
        \\);
        \\
        \\CREATE TABLE mesas (
        \\    periodo TEXT NOT NULL,
        \\    materia TEXT NOT NULL,
        \\    fecha TEXT NOT NULL,
        \\    presidente TEXT,
        \\    vocal TEXT,
        \\    PRIMARY KEY (periodo, materia, fecha),
        \\    FOREIGN KEY (periodo, materia) REFERENCES cursos(periodo, materia),
        \\    FOREIGN KEY (presidente) REFERENCES docentes(docente),
        \\    FOREIGN KEY (vocal) REFERENCES docentes(docente)
        \\);
    , aida_schema_ddl);
}
