--liquibase formatted sql
--changeset zigma:000004_add_docentes_esimportador
--comment: generated by Zigma; from-sha256=7714d21aebd288595753208e2d6140336e4af734565ce9711380218bc2c65664; to-sha256=2271a0b9f066067a5e013e087ae82ab0607327bc64296877071983c0c522e7a4

ALTER TABLE "docentes" ADD COLUMN "esImportador" BOOLEAN;

