--liquibase formatted sql
--changeset zigma:000002_add_docentes_telefono
--comment: generated by Zigma; from-sha256=2f53b8aa619d6adfcd05835e2bcadee50fa46feb4919e25b0c3adecfa7bb35f9; to-sha256=d90b119501495c80249a8faa04c57d9d888dbc136132ad1be200c78ad7e6062f

ALTER TABLE "docentes" ADD COLUMN "telefono" TEXT;

