--liquibase formatted sql
--changeset zigma:000003_add_docentes_experiencia
--comment: generated by Zigma; from-sha256=d90b119501495c80249a8faa04c57d9d888dbc136132ad1be200c78ad7e6062f; to-sha256=83989128c7df6892319e5383c09c5912577569454fc9198c9a5d16064aa61f0b

ALTER TABLE "docentes" ADD COLUMN "experiencia" BIGINT;

